# Generated by Django 3.1.2 on 2020-10-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('watch', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
