# Generated by Django 3.1.2 on 2020-10-23 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201022_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
