# Generated by Django 3.1.2 on 2020-10-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_user_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishlist',
            new_name='watchlist',
        ),
    ]
