# Generated by Django 3.1.2 on 2020-10-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201023_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
